import type { Metadata } from "next";
import ApolloProvider from "./auth/ApolloProvider";
import AuthProvider from "./auth/Provider";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <ApolloProvider>
          <body>{children}</body>
        </ApolloProvider>
      </AuthProvider>
    </html>
  );
}
