import type { Metadata } from "next";
import ApolloProvider from "./auth/ApolloProvider";
import AuthProvider from "./auth/Provider";
import QueryClientProvider from "./providers/QueryClientProvider";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools/production";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <ApolloProvider>
          <QueryClientProvider>
            <body>
              {children}
              <ReactQueryDevtools
                initialIsOpen={false}
                buttonPosition="top-right"
              />
            </body>
          </QueryClientProvider>
        </ApolloProvider>
      </AuthProvider>
    </html>
  );
}
