import { GridCellKind } from "@glideapps/glide-data-grid";
import { GridJsonType } from "../TableComponentGlide/types";
export const canvasIndexGridData: GridJsonType = {
  gridData: [
    {
      id: 1,
      name: "ValidationSet1",
      friendlyName: "Validation Set One",
      description: "Description of Validation Set One",
      createdBy: "admin",
      modifiedBy: "admin",
      dateCreated: "25/03/2024",
      dateModified: "26/03/2024",
    },
    {
      id: 2,
      name: "ValidationSet2",
      friendlyName: "Validation Set Two",
      description: "Description of Validation Set Two",
      createdBy: "admin",
      modifiedBy: "admin",
      dateCreated: "25/03/2024",
      dateModified: "26/03/2024",
    },
  ],
  selectedRow: [],

  columnConfiguration: [
    {
      title: "Id",
      id: "id",
      kind: GridCellKind.Number,
      index: 0,
      isDraggable: false,
      contentAlign: "left",
      hasMenu: false,
    },
    {
      title: "Friendly Name",
      id: "friendlyName",
      kind: GridCellKind.Text,
      index: 1,
      isDraggable: false,
      contentAlign: "left",
      isResizable: false,
      isEdittable: false,
    },
    {
      title: "Description",
      id: "description",
      kind: GridCellKind.Text,
      index: 1,
      isDraggable: false,
      contentAlign: "left",
      isResizable: false,
      isEdittable: false,
    },
    {
      title: "Created By",
      id: "createdBy",
      kind: GridCellKind.Text,
      index: 1,
      isDraggable: false,
      contentAlign: "left",
      isResizable: false,
      isEdittable: false,
    },
    {
      title: "Modified By",
      id: "modifiedBy",
      kind: GridCellKind.Text,
      index: 1,
      isDraggable: false,
      contentAlign: "left",
      isResizable: false,
      isEdittable: false,
    },
    {
      title: "Date Created",
      id: "dateCreated",
      kind: GridCellKind.Text,
      index: 1,
      isDraggable: false,
      contentAlign: "left",
      isResizable: false,
      isEdittable: false,
    },
    {
      title: "Date Modified",
      id: "dateModified",
      kind: GridCellKind.Text,
      index: 1,
      isDraggable: false,
      contentAlign: "left",
      isResizable: false,
      isEdittable: false,
    },
  ],
  gridConfiguration: {
    showEditActionColumn: true,
    // isFiltering: false,
    // isSorting: true,
    // isEdittable: true,
    //isDraggableColumn: true,
    // isRowExpandable: false,
    // isResizableColumn: true,
    // isFillHandle: true,
    //isRowAppended: true,
    // isFreezeColumn: null,
    // isDeletable: false,
    // isPagination: false,
    // isTooltip: true,
    // isDraggableRow: false,
    // isVerticalBorder: false,
    // isTextWrap: false,
    // isRowSelectable: true,
    // isSearchable: false,
    // isFreezeRow: null,
    // isGroupedColumn: true,
    // isGroupNameEditable: false,
    // isHeaderlessGrid: false,
    // isColumnStretched: true,
    // canUndoRedo: true,
    // isRowHovered: true,
    // isCellSelectable: true,
    // isContextMenu: true,
  },
};
