import {
  CustomCellKindEnum,
  GridJsonType,
} from "@/app/uiComponents/TableComponentGlide/types";
import { GridCellKind } from "@glideapps/glide-data-grid";

export const DashboardJson: GridJsonType = {
  gridData: [],
  selectedRow: [],
  columnConfiguration: [
    {
      title: "Date",
      id: "Date",
      kind: GridCellKind.Custom,
      subkind: CustomCellKindEnum.DatePickerCell,
      index: 1,
    },
    {
      title: "Supplier",
      id: "Supplier",
      kind: GridCellKind.Text,
      index: 2,
    },
    {
      title: "File name",
      id: "Filename",
      kind: GridCellKind.Text,
      index: 3,
    },
    {
      title: "Matched",
      id: "Matched",
      kind: GridCellKind.Number,
      index: 4,
    },
    {
      title: "Unmatched",
      id: "Unmatched",
      kind: GridCellKind.Number,
      index: 5,
    },
    {
      title: "Status",
      id: "Status",
      kind: GridCellKind.Text,
      // subkind: CustomCellKindEnum.BadgeCell,
      // options: [
      //   { value: "Processing", label: "Processing", color: "yellow" },
      //   { value: "Failed", label: "Failed", color: "red" },
      //   { value: "Completed", label: "Completed", color: "green" },
      // ],
      index: 6,
    },
    {
      title: "Uploaded By",
      id: "UploadedBy",
      kind: GridCellKind.Text,
      index: 7,
    },
  ],
  gridConfiguration: {
    isFiltering: false,
    isSorting: true,
    isEdittable: false,
    isDraggableColumn: false,
    isRowExpandable: false,
    isResizableColumn: true,
    isFillHandle: false,
    isRowAppended: false,
    isFreezeColumn: null,
    isPagination: true,
    isTooltip: false,
    isDraggableRow: false,
    isVerticalBorder: false,
    isTextWrap: false,
    isRowSelectable: false,
    // isSearchable: true,
    isFreezeRow: null,
    isGroupedColumn: false,
    isGroupNameEditable: false,
    isColumnStretched: true,
    canUndoRedo: false,
    isRowHovered: false,
    isCellSelectable: true,
    isContextMenu: false,
    showEditActionColumn: false,
    showMoreActionColumn: false,
    showViewActionColumn: true,
    showDeletableButton: false,
    isHeaderContextMenu: true,
  },
};
